pipeline:
  00-generate-dockerfiles:
    commands:
    - pip install -r requirements.txt
    - python render.py "docker"
    image: python:3.6.5-alpine3.7
  01-fix-dockerfiles-non-master:
    commands:
    - echo $DRONE_COMMIT_BRANCH
    - sed -i "s|captn3m0/drone-meta-ci-docker-build:|captn3m0/drone-meta-ci-docker-build:$DRONE_COMMIT_BRANCH|"
      *.Dockerfile
    image: alpine:3.7
    when:
      branch:
        exclude: master
      event: deployment
      status: success
  base-3.5:
    dockerfile: base-3.5.Dockerfile
    image: plugins/docker
    repo: captn3m0/drone-meta-ci-docker-build
    secrets:
    - DOCKER_USERNAME
    - DOCKER_PASSWORD
    tags: ${DRONE_COMMIT_BRANCH##master}base-3.5
    when:
      environment:
      - base-3.5
      event: deployment
      status: success
  base-3.6:
    dockerfile: base-3.6.Dockerfile
    image: plugins/docker
    repo: captn3m0/drone-meta-ci-docker-build
    secrets:
    - DOCKER_USERNAME
    - DOCKER_PASSWORD
    tags: ${DRONE_COMMIT_BRANCH##master}base-3.6
    when:
      environment:
      - base-3.6
      event: deployment
      status: success
  base-3.7:
    dockerfile: base-3.7.Dockerfile
    image: plugins/docker
    repo: captn3m0/drone-meta-ci-docker-build
    secrets:
    - DOCKER_USERNAME
    - DOCKER_PASSWORD
    tags: ${DRONE_COMMIT_BRANCH##master}base-3.7
    when:
      environment:
      - base-3.7
      - python-3.6
      event: deployment
      status: success
  lint:
    commands:
    - apk add --no-cache curl
    - curl -sL -o /usr/bin/hadolint "https://github.com/hadolint/hadolint/releases/download/v$HADOLINT_VERSION/hadolint-Linux-x86_64"
    - chmod 700 /usr/bin/hadolint
    - hadolint *.Dockerfile
    - echo "Making sure branch name doesn't contain a slash"
    - echo $DRONE_COMMIT_BRANCH | grep -v "/"
    environment:
      HADOLINT_VERSION: 1.6.5
    image: alpine:3.7
    when:
      event: push
  python-3.6:
    dockerfile: python-3.6.Dockerfile
    image: plugins/docker
    repo: captn3m0/drone-meta-ci-docker-build
    secrets:
    - DOCKER_USERNAME
    - DOCKER_PASSWORD
    tags: ${DRONE_COMMIT_BRANCH##master}python-3.6
    when:
      environment:
      - python-3.6
      event: deployment
      status: success
