ENV GOSU_VERSION="1.10"
ENV ARCH="amd64"

RUN echo "* Installing deps" && \
    apk add --no-cache \
    bash \
    build-base \
    ca-certificates \
    coreutils \
    curl \
    dumb-init \
    git \
    libffi-dev \
    linux-headers \
    openssl \
    openssl-dev \
    py-pip \
    python \
    python-dev
